### ISSUE TITLE
Method in stack trace cannot localization

### ISSUE THREAD

**Issue by AnonymousUser0407** [Gu-Youngfeng/EffciencyMinner#5]
Considering the following stack trace in io_mutants.txt,

```java
testSortArrayNull(org.apache.commons.io.comparator.CompositeFileComparatorTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.RuntimeException: null
  at org.apache.commons.io.comparator.AbstractFileComparator.sort(AbstractFileComparator.java:48)
  at org.apache.commons.io.comparator.CompositeFileComparator.sort(CompositeFileComparator.java:45)
  at org.apache.commons.io.comparator.ComparatorAbstractTestCase.testSortArrayNull(ComparatorAbstractTestCase.java:96)
  ...
```

The question is we CANNOT localize the method `sort()` in class `CompositeFileComparator` at line 45, because line 45 is the declaration line of class `CompositeFileComparator`. So directly use spoon to analyze `CompositeFileComparator.sort()` will return a null result, so how do it happens and how can we deal with it?

- Partial code in CompositeFileComparator,

```java
...
public class CompositeFileComparator extends AbstractFileComparator implements Serializable {  /** Line 45*/
 /** Line 46*/
    private static final long serialVersionUID = -2224170307287243428L;  /** Line 47*/
    private static final Comparator<?>[] NO_COMPARATORS = {};            /** Line 48*/
...
```

- Partial code in AbstractFileComparator,

```java
abstract class AbstractFileComparator implements Comparator<File> {

    public File[] sort(final File... files) {
        if (files != null) {
            Arrays.sort(files, this);
        }
        if (files == null) { 
            throw new RuntimeException(); /** LINE 48 */
        }
        return null;
    }
    ...
```

**Comment by AnonymousUser0407** [comment]
In stack trace, is it meaningful if the exception point is located in the line of the declaration of class?

Should we **1)** ignore this location or **2)** process this problem?

**Comment by Gu-Youngfeng** [comment]
Good question!

**Comment by Gu-Youngfeng** [comment]
Got the reason! `CompositeFileComparator` actually doesn't have method `sort()` at line 45, But, `CompositeFileComparator` is extended with its supper class `AbstractFileComparator`, which has the method `sort()` at line 43. 

That is to say, `CompositeFileComparator` inherited the method `sort()` of `AbstractFileComparator`! Hence, when the exception is thrown, this line 45 is recorded in stack trace.

The solution might be **analyzing the method sort() in its supper class**.

**Comment by Gu-Youngfeng** [comment]
The related issues are as follows,
- [How to get supper class in spoon?](https://github.com/INRIA/spoon/issues/2084) [GitHub]
- [Mysterious Location in Java stack trace?](https://stackoverflow.com/questions/50920229/mysterious-location-in-java-stack-trace#comment88840108_50920229) [StackOverflow]

**Comment by Gu-Youngfeng** [comment]
Due to this inherited method problem, the class `Efforter` will also throw the Exception,

```
java.lang.Exception
	at cn.edu.whu.cstar.timer.MEDAnalyzer.<init>(MEDAnalyzer.java:763)
	at cn.edu.whu.cstar.efforter.LineCounter.countingAllMethodLine(LineCounter.java:38)
	at cn.edu.whu.cstar.efforter.Efforter.counter(Efforter.java:95)
	at cn.edu.whu.cstar.efforter.Efforter.main(Efforter.java:27)
```

So the complete final solution is :

- [x] Analysis the inherited method in its supper class in feature extraction process
- [x] Ignore the inherited method in  effort counting process.
